const fs = require('fs');
const path = require('path');

function createSamplePdf(title, subtitle) {
  const content = `BT /F1 22 Tf 72 710 Td (${title}) Tj /F1 14 Tf 0 -36 Td (${subtitle}) Tj /F1 12 Tf 0 -30 Td (Generated by The Study Vault - Semester Survival Kit) Tj ET`;
  const streamLength = Buffer.byteLength(content);
  
  return `%PDF-1.4
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj
3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj
4 0 obj << /Length ${streamLength} >>
stream
${content}
endstream
endobj
5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000244 00000 n 
0000000370 00000 n 
trailer << /Size 6 /Root 1 0 R >>
startxref
450
%%EOF`;
}

const uploadsDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });

const seedMaterials = [
  {
    id: "mat-aiml-1",
    subject: "AIML",
    category: "Notes",
    title: "Unit 1: Neural Networks & Backprop Deep Dive",
    originalFilename: "AIML_Unit1_Notes.pdf",
    storageFilename: "seed_aiml_unit1.pdf",
    fileType: "pdf",
    pdfTitle: "AIML - Unit 1 Notes: Neural Networks",
    pdfSubtitle: "Loss functions, Backpropagation, Gradient Descent"
  },
  {
    id: "mat-aiml-2",
    subject: "AIML",
    category: "PYQs",
    title: "Midsem 2025 Solved PYQ Paper",
    originalFilename: "AIML_Midsem_2025_Solved.pdf",
    storageFilename: "seed_aiml_midsem.pdf",
    fileType: "pdf",
    pdfTitle: "AIML Midsem 2025 - Solved Questions",
    pdfSubtitle: "Complete solutions with grading scheme"
  },
  {
    id: "mat-aiml-3",
    subject: "AIML",
    category: "Labs",
    title: "Lab Manual & PyTorch Experiments 1-8",
    originalFilename: "AIML_Lab_Manual_Full.pdf",
    storageFilename: "seed_aiml_lab.pdf",
    fileType: "pdf",
    pdfTitle: "AIML Lab Manual - PyTorch Implementation",
    pdfSubtitle: "Codes and viva voice preparation questions"
  },
  {
    id: "mat-gai-1",
    subject: "GAI",
    category: "Notes",
    title: "Transformers & Attention Mechanism Architecture",
    originalFilename: "GAI_Transformers_Handwritten.pdf",
    storageFilename: "seed_gai_transformers.pdf",
    fileType: "pdf",
    pdfTitle: "GAI - Attention Is All You Need Notes",
    pdfSubtitle: "Self-attention, Multi-head attention, Positional Encoding"
  },
  {
    id: "mat-gai-2",
    subject: "GAI",
    category: "Important",
    title: "Prompt Engineering & RAG Cheatsheet",
    originalFilename: "Prompt_Engineering_RAG_CheatSheet.pdf",
    storageFilename: "seed_gai_cheatsheet.pdf",
    fileType: "pdf",
    pdfTitle: "Prompt Engineering & RAG Formulae",
    pdfSubtitle: "Vector databases, chunking strategies, chain-of-thought"
  },
  {
    id: "mat-qcai-1",
    subject: "QCAI",
    category: "Notes",
    title: "Qubits, Superposition & Entanglement Foundations",
    originalFilename: "QCAI_Foundations_Unit1.pdf",
    storageFilename: "seed_qcai_foundations.pdf",
    fileType: "pdf",
    pdfTitle: "QCAI - Qubits, Gates and Superposition",
    pdfSubtitle: "Bloch Sphere, Hadamard gate, CNOT, Bell States"
  },
  {
    id: "mat-qcai-2",
    subject: "QCAI",
    category: "PYQs",
    title: "Endsem 2024 Quantum Algorithm PYQs",
    originalFilename: "QCAI_Endsem_2024_PYQs.pdf",
    storageFilename: "seed_qcai_endsem.pdf",
    fileType: "pdf",
    pdfTitle: "QCAI Endsem 2024 Previous Year Questions",
    pdfSubtitle: "Deutsch-Jozsa, Grover search, and Shor algorithm"
  },
  {
    id: "mat-cv-1",
    subject: "CV",
    category: "Notes",
    title: "CNNs, Convolutions & Edge Detection Filters",
    originalFilename: "CV_CNN_Convolutions.pdf",
    storageFilename: "seed_cv_cnn.pdf",
    fileType: "pdf",
    pdfTitle: "Computer Vision - Convolutions and Pooling",
    pdfSubtitle: "Sobel, Prewitt, Canny Edge detector, and ResNet"
  },
  {
    id: "mat-cv-2",
    subject: "CV",
    category: "Labs",
    title: "OpenCV Python Lab Codes & Output Screenshots",
    originalFilename: "CV_OpenCV_Lab_Guide.pdf",
    storageFilename: "seed_cv_opencv.pdf",
    fileType: "pdf",
    pdfTitle: "CV Lab Manual - OpenCV 4.x Solutions",
    pdfSubtitle: "Filtering, Morphological ops, Contour detection"
  },
  {
    id: "mat-aps-1",
    subject: "APS",
    category: "Notes",
    title: "Distributions Cheatsheet (Binomial, Poisson, Normal)",
    originalFilename: "APS_Distributions_Mastery.pdf",
    storageFilename: "seed_aps_dist.pdf",
    fileType: "pdf",
    pdfTitle: "APS - Probability Distributions & Moments",
    pdfSubtitle: "Mean, Variance, MGF, Central Limit Theorem"
  },
  {
    id: "mat-aps-2",
    subject: "APS",
    category: "Important",
    title: "Hypothesis Testing & Confidence Intervals Formulae",
    originalFilename: "APS_Hypothesis_Testing_Formulas.pdf",
    storageFilename: "seed_aps_hyp.pdf",
    fileType: "pdf",
    pdfTitle: "APS - Hypothesis Testing Z-test, T-test, Chi-square",
    pdfSubtitle: "Critical values, p-values, degrees of freedom"
  }
];

const vaultData = [];

for (const mat of seedMaterials) {
  const filePath = path.join(uploadsDir, mat.storageFilename);
  const pdfData = createSamplePdf(mat.pdfTitle, mat.pdfSubtitle);
  fs.writeFileSync(filePath, pdfData);
  const stats = fs.statSync(filePath);

  vaultData.push({
    id: mat.id,
    subject: mat.subject,
    category: mat.category,
    title: mat.title,
    originalFilename: mat.originalFilename,
    storageFilename: mat.storageFilename,
    fileType: mat.fileType,
    size: stats.size,
    createdAt: new Date().toISOString()
  });
}

const dataDir = path.join(__dirname, 'data');
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

fs.writeFileSync(path.join(dataDir, 'vault.json'), JSON.stringify(vaultData, null, 2));
console.log('Seed files and vault.json generated successfully!');
